### ISSUE TITLE
Running a simple test with libgaba

### ISSUE THREAD

**Issue by smarco** [ocxtal/libgaba#3]
Hi,

I'm trying to run a simple test using libgaba. Despite my numerous efforts to follow the README.md and some examples/unit-tests I found within the code, I haven't managed to run the following simple alignment test.

I would greatly appreciate some help here as I cannot find any documentation, guide or help that can help me running this library.

void libgaba_test() {
  // Initialize sequences
  char pattern[] = "ACGTACGTACGT";
  char text[] = "ACGTACAAAGTACGT";
  uint8_t* a = malloc(strlen(pattern)+1);
  uint8_t* b = malloc(strlen(text)+1);
  int i;
  for (i=0;i<strlen(pattern);++i) {
    switch (pattern[i]) {
      case 'A': a[i] = 0x01; break;
      case 'C': a[i] = 0x02; break;
      case 'G': a[i] = 0x04; break;
      case 'T': a[i] = 0x08; break;
    }
  }
  a[strlen(pattern)] = '\0';
  for (i=0;i<strlen(text);++i) {
    switch (text[i]) {
    case 'A': a[i] = 0x01; break;
    case 'C': a[i] = 0x02; break;
    case 'G': a[i] = 0x04; break;
    case 'T': a[i] = 0x08; break;
    }
  }
  b[strlen(text)] = '\0';
  // Initialize a global context
  gaba_t* ctx = gaba_init(GABA_PARAMS(.xdrop = 100,GABA_SCORE_SIMPLE(1,4,2,1)));
  struct gaba_section_s asec = gaba_build_section(0, a, strlen(a));
  struct gaba_section_s bsec = gaba_build_section(2, b, strlen(b));
  // Align
  void const *lim = (void const *)0x800000000000;
  gaba_dp_t *dp = gaba_dp_init(ctx, lim, lim);
  struct gaba_section_s *ap = &asec, *bp = &bsec;
  struct gaba_fill_s *f = gaba_dp_fill_root(dp, ap, 0, bp, 0);
  // Trace & Print results
  char* c = (char *) malloc(strlen(pattern)+strlen(text)); // Initialize CIGAR
  struct gaba_alignment_s *r = gaba_dp_trace(dp, f, NULL, NULL); // Trace
  gaba_dp_print_cigar_forward(ut_printer, c, r->path->array, 0, r->path->len);
  printf("CIGAR=%s\n",c);
  // Free
  free(a);
  free(b);
  free(c);
  gaba_dp_clean(dp);
  gaba_clean(ctx);
}

Thank you so much in advance.
Cheers,

**Comment by ocxtal** [comment]
Hi @smarco,

Sorry for bothering you, it seems you need to pass "margin" segment after each of pattern and text strings to reach down to the end of the sequences. `example.c` in the merge-dev branch shows how to connect the margin sequences after the sequences to be aligned. Could you fetch the merge-dev branch and run the example code by `make all && ./example`?

I will merge some of the merge-dev branch and update the readme. Sorry for inconvenience.

Hajime Suzuki

**Comment by ocxtal** [comment]
I've updated the README.

Thanks,

**Comment by smarco** [comment]
Still, I've modified example.c as to delete the 'C' in the string b.
That is,

	char const *a = "\x01\x08\x01\x08\x01\x08";			/* 4-bit encoded "ATATAT" */
	char const *b = "\x01\x08\x01\x01\x08";			       /* 4-bit encoded "ATACAT" */
	char const t[64] = { 0 };							/* tail array */

In that case, the example returns:

score(6), path length(6)
3M

Which is not what I would expect from aligning those 2 string.
Any help would be appreciated.

**Comment by ocxtal** [comment]
If the score parameters was not modified from in example.c, it seems it returned a correct result.

* the library calculates *semi-global* (left-end closed and right-end open; not local nor global), so the two matching bases (AT) are not aligned because gap penalty for one column (5 + 1 = 6) < match award for two bases (2 * 2 = 4). It would return `3M1D2M` and path length = 11 when the score parameters are set (2, 3, 2, 1).
* the path length is *bit-string length* stored in `path` array. the path array contains 101010 (or 0x15 filled from LSb) and is dumped as `3M`.

If this contradicts to your understanding, I would appreciate if you tell me the details. It would be helpful refining the documentation.

Thanks,

Hajime Suzuki

**Comment by smarco** [comment]
Ahh! Sorry, my bad. You are definitely right.

Nevertheless, I still don't get it right.
The following code is still not working (though the example is).
See that it's a small modification from the example.

void test() {
  char pattern[] = "ACGTACGT";
  char text[] = "ACGTCCGT";
  // Initialize sequences
  uint8_t* const a = malloc(strlen(pattern) + 65);
  uint8_t* const b = malloc(strlen(text) + 65);
  uint8_t* const t = malloc(64); // tail array
  int i;
  for (i=0;i<strlen(pattern);++i) {
    switch (pattern[i]) {
      case 'A': a[i] = 1; break;
      case 'C': a[i] = 2; break;
      case 'G': a[i] = 4; break;
      case 'T': a[i] = 8; break;
    }
  }
  a[strlen(pattern)] = '\0';
  for (i=0;i<strlen(text);++i) {
    switch (text[i]) {
    case 'A': a[i] = 1; break;
    case 'C': a[i] = 2; break;
    case 'G': a[i] = 4; break;
    case 'T': a[i] = 8; break;
    }
  }
  b[strlen(text)] = '\0';
  // Initialize a global context
  gaba_t* ctx = gaba_init(GABA_PARAMS(.xdrop = 100,GABA_SCORE_SIMPLE(1,4,2,1)));
  struct gaba_section_s asec = gaba_build_section(0, a, strlen(pattern) + 65);
  struct gaba_section_s bsec = gaba_build_section(2, b, strlen(text) + 65);
  struct gaba_section_s tail = gaba_build_section(4, t, 64);
  // Align
  void const *lim = (void const *)0x800000000000;
  gaba_dp_t *dp = gaba_dp_init(ctx, lim, lim);
  struct gaba_section_s *ap = &asec, *bp = &bsec;
  struct gaba_fill_s *f = gaba_dp_fill_root(dp, ap, 0, bp, 0, UINT32_MAX);
  // Until X-drop condition is detected
  struct gaba_fill_s const *m = f;          /* track max */
  while((f->status & GABA_TERM) == 0) {
    if(f->status & GABA_UPDATE_A) { ap = &tail; } /* substitute the pointer by the tail section's if it reached the end */
    if(f->status & GABA_UPDATE_B) { bp = &tail; }
    f = gaba_dp_fill(dp, f, ap, bp, UINT32_MAX);  /* extend the banded matrix */
    m = f->max > m->max ? f : m;          /* swap if maximum score was updated */
  }
  // Trace & Print results
  struct gaba_alignment_s *r = gaba_dp_trace(dp,
    m,                        /* section with the max */
    NULL                      /* custom allocator: see struct gaba_alloc_s in gaba.h */
  );
  printf("score(%ld), path length(%lu)\n", r->score, r->plen);
  gaba_print_cigar_forward(
      printer, (void *)stdout, /* printer */
    r->path, /* bit-encoded path array */
    0,       /* offset is always zero */
    r->plen  /* path length */
  );
  printf("\n");
  // Free
  free(a);
  free(b);
  free(t);
  gaba_dp_res_free(dp, r);
  gaba_dp_clean(dp);
  gaba_clean(ctx);
}

Any help would be greatly appreciated.
Thank you in advance and sorry for all the inconvenience.
Cheers,

**Comment by ocxtal** [comment]
It seems the encoding conversion loop for the sequence B is wrong; it writes to the buffer for sequence A.
```
for (i=0;i<strlen(text);++i) {
	switch (text[i]) {
		case 'A': b[i] = 1; break;
		case 'C': b[i] = 2; break;
		case 'G': b[i] = 4; break;
		case 'T': b[i] = 8; break;
	}
}
```

Resulted in the following:
```
% gcc debug.c -I.. -L.. -lgaba && ./a.out
score(4), path length(8)
4M
```

Also, sequence length fields on initializing the section objects should not include margins at the tail of the buffer (though it may not change the result in this case):
```
struct gaba_section_s asec = gaba_build_section(0, a, strlen(pattern));
struct gaba_section_s bsec = gaba_build_section(2, b, strlen(text));
```

Thanks,

**Comment by smarco** [comment]
Ah! I'm deeply sorry! That was a terrible mistake on mi side.
Sorry for the inconvenience.

Now, I just need to now the offset of the alignment (as r->path->offset doesn't exist) and if there is a way to report also the mismatches found.

Thank you so much for the feedback and the quick reply to all my issues.
Cheers,

**Comment by ocxtal** [comment]
Offset for each segment is found as `ppos` member in `struct gaba_segment_s`. It is directly used as the `offset` argument of the parse and dump functions.

The mismatches are not distinguished in the current parse / dump functions. It seems easy to add CIGAR dumper that discriminates match `=` and mismatch `X` so I will work on implementing another dump / parse function pair from now. If there is another preferred format to be converted from the path string (as a way to report also the mismatches found), please let me know. I will also consider implementing the function if it seems worthwhile.

Thanks,

**Comment by ocxtal** [comment]
I've added CIGAR printer `gaba_{print, dump}_xcigar_forward` in `parse-dev` branch. It outputs CIGAR with mismatching positions.

I modified the input sequences and added a dump_xcigar_forward call as follows:
```
char pattern[] = "ACGTACGTACGTACGT";
char text[] = "ACGTCCGTTACGTACGT";

gaba_print_xcigar_forward(printer, (void *)stdout, r->path, r->seg, &asec, &bsec);
printf("\n");
```

and the output was:
```
score(8), path length(33)
8M1I8M
4=1X3=1I8=
```

Thanks,

**Comment by smarco** [comment]
Thank you so much for all your help.
